services:
  # pgadmin_service:
  #   image: dpage/pgadmin4
  #   container_name: my-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@example.tld
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #   ports:
  #     - "15432:80"
  #   restart: always
  #   networks:
  #     - my-network
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - internal-network
  #     - nostr-daemon

  mmrelaypostgres:
    image: supabase/postgres:17.4.1.043
    container_name: mmrelaypostgres
    hostname: mmrelaypostgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/New_York
      # PGDATA: /var/lib/postgresql/data2
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - internal-network
      - nostr-daemon

  mmrelay:
    image: mmrelay
    container_name: mmrelay
    hostname: mmrelay
    environment:
      PG_CONN_STRING: postgres://postgres:postgres@mmrelaypostgres:5432/postgres
    ports:
      - "9090:9090"
    restart: always
    networks:
      - nostr-daemon
      - internal-network

networks:
  nostr-daemon:
    external: true
  internal-network:
      internal: true

volumes:
  pgadmin-data:
  postgres-data:
